Updated language check script.

diff --git a/bin/language-check b/bin/language-check
--- a/bin/language-check
+++ b/bin/language-check
@@ -3,14 +3,47 @@
 input_file="$1"
 lang=EN-US
 
-if grep -i --quiet '\(pagarbiai\| ir\|, kad\|, nes\| bei\| arba\|, bet|tačiau\) ' "$input_file"; then
+if grep -i --quiet ' \(ir\|bei\|arba\|tačiau\|pagarbiai\) \|, \(kad\|nes|bet\|o\) \|[ąčęėįšųūž]' "$input_file"; then
 	lang=LT
 fi
+
+run_language_tool_server_if_needed() {
+    if lsof -i tcp@localhost:8081 &>/dev/null; then
+        return
+    fi
+
+    language_check_path="$(
+    "$HOME/.dotfiles/python/env/bin/python" <<EOF
+try:
+    import language_check
+    print(language_check.__file__)
+except:
+    pass
+EOF
+    )"
+    if [ -n "$language_check_path" ]; then
+        language_check_path="$(dirname "$language_check_path")"
+    fi
+
+    if [ -z "$language_check_path" ]; then
+        echo "could not find language check" &1>&2
+        exit 1
+    fi
+
+    language_tool_path="$(echo "${language_check_path}/LanguageTool-"*)"
+    java \
+        -cp $HOME/.dotfiles/python/env/lib/python3.4/site-packages/language_check/LanguageTool-2.7/languagetool-server.jar \
+        org.languagetool.server.HTTPServer \
+        --port 8081 &>/dev/null &
+    disown %1
+}
+
+run_language_tool_server_if_needed
 
 $HOME/.dotfiles/python/env/bin/language-check -l "$lang" -d WHITESPACE_RULE <(\
 	cat "$input_file" \
 		| awk '/``/{i++;print"";next}{if(i%2){print""}else{print}}' `# markdown fences` \
-		| sed -E -e 's/^(Date|From|To|Subject|X-Mailer): .*$//g' `# mail headers` \
+		| sed -E -e 's/^(Date|CC|BCC|From|To|Subject|X-Mailer): .*$//g' `# mail headers` \
 		| sed -e 's/^>.*//g' `# mail comments` \
 		| detex -cn `# latex stuff` \
 	) | sed -e 's/^[^:]*:/'"$(echo "$1" | sed -e 's/[\/&]/\\&/g')"':/g'
